### ISSUE TITLE
Installation issue with jest when using Node v14

### ISSUE THREAD

**Issue by rowild** [TYPO3-Headless/nuxt-typo3#135]
First-time user here! 
It seems jest has a version conflict. This is my terminal:

![Bildschirmfoto 2021-07-21 um 08 25 59](https://user-images.githubusercontent.com/213803/126441800-3e23f711-6553-4ad6-981d-9176719c68a9.png)

The [vue-jest documentation](https://github.com/vuejs/vue-jest) mentions that, if used with jest > 24 and babel-jest (which vue-jest seems to do), `babel-core@bridge` has to be required, too. However, installing it `npm install --save-dev babel-core@bridge` does not work, either. Not sure how this can be fixed - any ideas?

UPDATE 2021-07-23:
This error only happens when using Node v14. Everything works fine with Node v12.

**Comment by mercs600** [comment]
I have run the same command with the same selection on my local machine and I have also run https://github.com/TYPO3-Initiatives/pwa-demo where we're using jest also and it works correct. Please try it with pwa-demo and let me know if you have the same issue

**Comment by rowild** [comment]
I keep getting the error as shown in my screenshot above. The TYPO3 distribution pwa-demo does work, however. But I do not see that `create-nuxt-typo3` is used there...
Anyway: re you sure you tested with `npx create-nuxt-typo3` and not `npx create-nuxt-app`? because
BTW: This really only happens when choosing `jest` as testing ramework. Choosing `AVA` does NOT cause any problems.

**Comment by mercs600** [comment]
@rowild I'm pretty sure I have run `npx create-nuxt-typo3`.
pwa-demo also use this script but as `npm init` which is the same what `npx` and there we also use jest for testing but we have all answers here https://github.com/TYPO3-Initiatives/pwa-demo/blob/master/front/recommended.json
pwa-demo init you can find here https://github.com/TYPO3-Initiatives/pwa-demo/blob/master/.ddev/commands/web/front#L19 

regarding version - we are not synchronize create-nuxt-typo3 with create-nuxt-app. 

In that case I recommend use crate-nuxt-app and install nuxt-typo3 manually - much simpler -> https://typo3-initiatives.github.io/nuxt-typo3/getting-started.html#installation

**Comment by rowild** [comment]
I could narrow down the problem. It happens with Node v14, but not with Node v12. Could you please try again and provide feedback? Because it is a reoccurring reproducible problem that should be made aware of. Thanks!
(BTW: I know my way around installing the ext. I would just like to contribute to the ext by at least searching for errors and providing some proofreading.)
