### ISSUE TITLE
Get nuxt2 working with composition api plugin

### ISSUE THREAD

**Issue by thomasv** [TYPO3-Headless/nuxt-typo3#167]
When adding the @nuxtjs/composition-api and running the dev server (`npm run dev`), it shows the error:

```
ERROR  Cannot read property 'includes' of undefined
at node_modules/nuxt-typo3/lib/module.js:26:60
```

In the `module.js` in `this.options.extendPlugins` the destructuring to `{ src }` fails, because the composition api plugin has not the expected object structure. It is only a string containing the plugin path.

I'm not sure, if this is potentially a composition-api issue or if this could be handled in nuxt-typo3.

Minimal project setup for reproducing the issue:
https://github.com/thomasv/nuxt-typo3-with-composition-api

**Comment by mercs600** [comment]
@thomasv we have fixed it, you can fetch v0.9.5-alpha.0 
https://github.com/TYPO3-Initiatives/nuxt-typo3/releases/tag/v0.9.5-alpha.0 
https://www.npmjs.com/package/nuxt-typo3/v/0.9.5-alpha.0
