### ISSUE TITLE
Preview Hidden pages

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [TYPO3-Headless/nuxt-typo3#242]
I didn't found a way to make it possible to preview hidden pages. Is there already a way to do that? 

Otherwise I would say this cut out a pretty important feature of TYPO3. I have a customer which desperatly needs to see a preview of hidden pages.

**Comment by oskardydo** [comment]
Generally you should be able to preview hidden pages. 

But you need to have cookies properly set up on frontend. 
Is your frontend and backend applications on the same domain? (ex. backend is accessible by suffix domain.com/headless)

**Comment by MichaelNussbaumerGOWEST** [comment]
We use different Servers for Backend and Frontend. The solution was to set the cookieDomain via AdditionalConfiguration.php

`$GLOBALS['TYPO3_CONF_VARS']['BE']['cookieDomain'] = '.example.com';`
