### ISSUE TITLE
Remove GET parameters from API requests

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [TYPO3-Headless/nuxt-typo3#247]
We should try to remove GET Parameters from the API requests. I have the issue right now on a Website, that a lot of old URLs coming with GET Parameters which are no longer important for the website, thats why I think we should remove them from the API requests. Also there are some old URLs with cHash Parameter which causes working pages to deliver 404 Responses. 

So make cHash maybe optional? In my setups cHash doesn't play a role anymore, so I would like to get rid of them aswell. 

But the majority of the GET Parameters (source_campaign [Salesforce], gclid [Google], ...) are not needed for the backend, so Requests are most propably also uncached for no reason for Users coming from some Ad Campaigns. 

What are your opinions?

**Comment by mercs600** [comment]
@MichaelNussbaumerGOWEST I totally agree with you, some part of GET params are not needed for the API. 
We could introduce configurable whitelist. I will back to you when we discuss it internally.
