### ISSUE TITLE
documentation jsconfig for alias '~typo3'

### ISSUE THREAD

**Issue by kubilaymelnikov** [TYPO3-Headless/nuxt-typo3#266]
Should something like this be added to the documentation?

```json
{
  "compilerOptions": {
    "paths": {
      "~typo3/*": ["./node_modules/nuxt-typo3/lib/*"]
    }
  }
}
```

**Comment by mercs600** [comment]
this is great idea, we can add it also here https://github.com/TYPO3-Headless/nuxt-typo3/blob/master/jsconfig.json
