### ISSUE TITLE
CeHtmlParser Dynamic Component

### ISSUE THREAD

**Issue by kubilaymelnikov** [TYPO3-Headless/nuxt-typo3#267]
Is there anything against using the dynamic component wrapper as default here?

[T3HtmlParser.vue](https://github.com/TYPO3-Headless/nuxt-typo3/blob/master/lib/components/T3HtmlParser/T3HtmlParser.vue)

```vue
<template>
  <component :is="tag" v-html="content" />
</template>

<script>
export default {
  name: 'CeHtmlParser',
  props: {
    content: {
      type: String,
      default: '',
    },
    tag: {
      type: String,
      default: 'div',
    },
  },
}
</script>
```

**Comment by mercs600** [comment]
@kubilaymelnikov nope, I'm aware that change might be helpful in some cases
