### ISSUE TITLE
<t3-dynamic> documentation missing

### ISSUE THREAD

**Issue by spot-mathis** [TYPO3-Headless/nuxt-typo3#277]
Hello,

I would like to customize the Container arround every T3CeXXX, so I thought to customize the <t3-dynamic> component, but 
1. I don't know how (maybe you can tell me here),
2.  I don't know if it's the right place for dealing with margins, classnames, ... of the wrapper arround every T3CeXXX component

That Link is dead: https://typo3-headless.github.io/nuxt-typo3/frontend/lib/components/content/CeRenderer.js
Got it from here (at https://typo3-headless.github.io/nuxt-typo3/frontend/)
![image](https://user-images.githubusercontent.com/94961566/191705203-101d3b3d-a4da-4fc7-8b59-6d07becd7bb9.png)

**Comment by mercs600** [comment]
@spot-mathis the file you are looking for is https://github.com/TYPO3-Headless/nuxt-typo3/blob/master/lib/components/T3Renderer/T3Renderer.js
This component is responsible for iterating through content array  from specific colPos (TYPO3 API) and creating dynamic component based on current item type. You have to notice there is also condition to check whether it should render ContentElement Frame or not. 
```js
  // render loop of content elements
    return ctx.props.content.map((element, index) =>
      ctx.props.frame && element.appearance.frameClass !== 'none'
        ? renderFrame(element, index)
        : renderComponent(element, index)
    )
```
You can override this component in regular way like you override global components. 
This file is written in render function, but you can use regular template in your own version.

**Comment by mercs600** [comment]
So to override container which is responsible for wrapping of all content elements you should override page file which is called `_.vue` in pages directory (https://github.com/TYPO3-Headless/nuxt-typo3/blob/master/lib/pages/_.vue) - just copy this file to your application
there is: 
```html
<template>
  <div>
    <t3-dynamic
      :data="t3page.content"
      :type="t3page.appearance.backendLayout"
      layout
    />
  </div>
</template>
```
so this div you see above is wrapper for all content elements.

To handle margins between content elements we use T3Frame Component https://github.com/TYPO3-Headless/nuxt-typo3/blob/master/lib/components/T3Frame/T3Frame.js -> this component takes fields from appearance of current content element and setup specific classes: 

```js
class: [
          't3-ce-frame',
          `frame-${props.frameClass}`,
          `layout-${props.layout}`,
          `space-before-${
            props.spaceBefore.length ? props.spaceBefore : 'default'
          }`,
          `space-after-${
            props.spaceAfter.length ? props.spaceAfter : 'default'
          }`
        ],
```

We use fields space-before, space-after to setup specific margins, we use also frame and layout classes to do some specific work.

So to override single content element wrapper you can override T3Frame
