### ISSUE TITLE
Hash / onPage navigation results in getPages from backend

### ISSUE THREAD

**Issue by develth** [TYPO3-Headless/nuxt-typo3#288]
When creating an OnPage Menu and want to navigate on page via Hash-Navigation, the `contextMiddleware` decides on `isDynamicRoute(context.route)` to create a GET request and to load a page.

Maybe check on `isDynamicRoute`, if there is a hash set and it path differs from current path?

**Comment by mercs600** [comment]
@develth I see, this is related with https://github.com/TYPO3-Headless/nuxt-typo3/issues/247 and we are working on that.

**Comment by develth** [comment]
great, thx @mercs600 !

**Comment by mercs600** [comment]
@develth fixed with v1.1.0
