### ISSUE TITLE
Initial data vuex store is mixed up in multisite setup

### ISSUE THREAD

**Issue by denniswiemers** [TYPO3-Headless/nuxt-typo3#310]
After upgrading to TYPO3 11.5 alongside with nuxt-typo3 1.2.2 there is a strange behaviour in our production build, the initial data vuex store is sometimes mixed up between websites in SSR context. Resulting in showing the wrong navigation for the current website.

To reproduce this issue on a local machine just call two or three website domains of a multisite setup at once.

I tried different nuxt-typo3 versions and everything is working fine with versions below [v1.0.0-alpha.4](https://github.com/TYPO3-Headless/nuxt-typo3/releases/tag/v1.0.0-alpha.4) - Looks like the bug was first introduced in v1.0.0-alpha.4.

I couldnt figure out what exactly causes the issue so any help is appreciated.

**Comment by mercs600** [comment]
@denniswiemers I can't reproduce the issue.  
Additionally we have multisite configuration for one of our project and we did not notice it. 

My reproduce environment:
I have run frontend based on https://github.com/TYPO3-Headless/pwa-demo so one of the API endpoint is ddev site and another is api.t3pwa.com. I have correct SSR data each time when I refresh the page. No matter it is develop/production build. 

```js
typo3: {
    baseURL: process.env.NUXT_HOST,
    forms: true,
    i18n: {
      locales: ['en', 'pl', 'de'],
      locale: 'en',
      fallbackLocale: 'en'
    },
    domains: [
      {
        name: 'test.local', // name of your host
        baseURL: 'http://test.local',
        api: {
          baseURL: 'https://api.t3pwa.com/'
        },
        i18n: {
          locales: ['pl', 'en'],
          defaultLocale: 'pl'
        }
      },
      {
        name: 'test2.local', // name of your host
        baseURL: 'https://test2.local/',
        api: {
          baseURL: 'https://api.pwa-demo.ddev.site/'
        },
        i18n: {
          locales: ['en'],
          defaultLocale: 'en'
        }
      }
    ]
  },
```

Try to reproduce it the same way. Using PWA DEMO API and api.t3pwa.com on localhost and let me know if works
