### ISSUE TITLE
No error handling when trying to enter page with content-type other than json

### ISSUE THREAD

**Issue by mateusznarowski** [TYPO3-Headless/nuxt-typo3#319]
When accessing the TYPO3 panel page via `api.placeholder.com/typo3` and attempting to navigate to `placeholder.com/typo3` from a website, an HTTP 500 error is encountered. This error occurs because an attempt is being made to access the TYPO3 panel, which is a restricted URL and should not be accessed from a website.

**Comment by mateusznarowski** [comment]
#320

**Comment by mercs600** [comment]
closed with #321
