### ISSUE TITLE
Use "hookable" instead of "hable" to support nuxt@2.17.3

### ISSUE THREAD

**Issue by thomasv** [TYPO3-Headless/nuxt-typo3#338]
In nuxt@2.17.3 "hable" was replaced by "hookable", see https://github.com/nuxt/nuxt/pull/24426

lib/plugins/context.js uses hable directly - this leads to problems when using nuxt-typo3 with nuxt@2.17.3. I think this must be considered in a full upgrade of nuxt-edge or can you add hookable/hable as direct dependency?

**Comment by mercs600** [comment]
@thomasv it should be fixed with the 1.4.0
