### ISSUE TITLE
v2.0.3 release in NPM registry

### ISSUE THREAD

**Issue by ArcoMul** [TYPO3-Headless/nuxt-typo3#342]
Hi, could version 2.0.3 also be published on NPM? The latest version there is 2.0.2 it seems: https://www.npmjs.com/package/@t3headless/nuxt-typo3

Here in the repository I am seeing 2,0.3 with some bug fixes.

Thank you!

**Comment by mercs600** [comment]
@ArcoMul We have published the latest version, as well as the previous ones, publicly.
