### ISSUE TITLE
500 useT3Api is not defined

### ISSUE THREAD

**Issue by cehret** [TYPO3-Headless/nuxt-typo3#346]
Hello!
I have a very strange behavior when fetching a new installation with nuxt-typo3.
I got the error:
500
useT3Api is not defined
![500](https://github.com/user-attachments/assets/622a3d2c-e563-4383-8a5a-56290204ea55)

This happens if I checkout a running app from git, run npm install and nuxt dev, but it also happens if I setup a completely new app, like described here: https://t3headless.macopedia.io/nuxt-typo3/introduction: 
`npx nuxi@latest init -t gh:TYPO3-Headless/nuxt-typo3-starter <project-name>`

The same procedure worked some days ago, without any problems! So I can have the same app checked out from git on the same computer (it does not matter if macOS or Windows) twice - one checked out I guess about 1 or 2 weeks ago working and one checkt out today not working!

If I remove node_modules directory from the non-working installation and copy node_modules directory form a working (older) one, the non-working will work! I suspect it is a newer version of some package which is causing it to no longer work? But which one?

Any ideas how I can better narrow down the error? The consoles and the NuxtDevTools do not provide any valuable information for me :-(

**Comment by cehret** [comment]
today I can't even kickstart a new project 
https://github.com/user-attachments/assets/204a72c1-e078-445a-9c24-f22ecc832c6e

**Comment by mercs600** [comment]
@cehret we are working on it. 
Somehow, the composables we provided for autoimports are no longer being resolved.
As a temporary workaround, you can import our composables through the #typo3 alias.

```js
import { useT3Api } from '#typo3/composables/useT3Api'
```

**Comment by cehret** [comment]
cannot reproduce the issue anymore - it seems that the error has been fixed
